version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todoapi-example:
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    volumes:
      - ".:/todoapi-example/src/app/"